/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Image */
        post: operations["analyze_image_api_v1_analyze_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Document */
        post: operations["analyze_document_api_v1_analyze_document_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Claim */
        post: operations["analyze_claim_api_v1_analyze_claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Get job status. Investigators see any job; claimants see only their own jobs.
         */
        get: operations["get_job_status_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis Result */
        get: operations["get_analysis_result_api_v1_results__result_id__get"];
        put?: never;
        post?: never;
        /** Delete Analysis Result */
        delete: operations["delete_analysis_result_api_v1_results__result_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{result_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result Evidence */
        get: operations["get_result_evidence_api_v1_results__result_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{result_id}/report.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Json Report */
        get: operations["get_json_report_api_v1_results__result_id__report_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{result_id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pdf Report */
        get: operations["get_pdf_report_api_v1_results__result_id__report_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{result_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Result Timeline
         * @description Returns the chronological evidence timeline (§14.5) with contradictions and undated items.
         */
        get: operations["get_result_timeline_api_v1_results__result_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{result_id}/{name}/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Signed Url
         * @description Issue a short-lived signed URL for an artifact. Requires authentication.
         */
        get: operations["get_artifact_signed_url_api_v1_artifacts__result_id___name__url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{result_id}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Serve a generated artifact.
         *     - With valid sig+exp: verified HMAC signature.
         *     - Direct accessible paths: allowed for verified result artifacts.
         *     Strictly prevents directory traversal.
         */
        get: operations["get_artifact_api_v1_artifacts__result_id___name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Policies */
        get: operations["get_my_policies_api_v1_policies_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Claim */
        post: operations["create_claim_api_v1_claims_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Claims */
        get: operations["get_my_claims_api_v1_claims_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim Status */
        get: operations["get_claim_status_api_v1_claims__id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/evidence-timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim Evidence Timeline */
        get: operations["get_claim_evidence_timeline_api_v1_claims__id__evidence_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/resubmit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resubmit Evidence */
        post: operations["resubmit_evidence_api_v1_claims__id__resubmit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/fast-track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fast Track Claim */
        post: operations["fast_track_claim_api_v1_claims__id__fast_track_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/fast-track/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Fast Track Claim */
        post: operations["undo_fast_track_claim_api_v1_claims__id__fast_track_undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim Actions */
        get: operations["get_claim_actions_api_v1_claims__id__actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Claim Entities Endpoint
         * @description Returns normalized entities for a claim (§14.3, Prompt 8 Part 5).
         */
        get: operations["get_claim_entities_endpoint_api_v1_claims__id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{id}/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Claim Network Endpoint
         * @description Returns fraud ring network intelligence, shared entities, and CLM-NET evidence (§14.3, Prompt 10).
         */
        get: operations["get_claim_network_endpoint_api_v1_claims__id__network_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Triage Queue */
        get: operations["get_triage_queue_api_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{id}/decision/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Decision */
        post: operations["draft_decision_api_v1_results__id__decision_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Decision */
        post: operations["submit_decision_api_v1_results__id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/liveness/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Liveness Session
         * @description Issues a single-use random liveness session with 3 randomised challenges.
         *     Valid for 120 seconds. Requires claimant or investigator auth (P2-14).
         */
        post: operations["issue_liveness_session_api_v1_identity_liveness_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity/liveness/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Liveness Endpoint
         * @description Verifies 8-40 captured liveness frames against the issued session challenges.
         *     Requires claimant or investigator auth (P2-14).
         */
        post: operations["verify_liveness_endpoint_api_v1_identity_liveness_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Supported Languages
         * @description Returns list of supported Indian languages with codes, English names, and native names.
         */
        get: operations["get_supported_languages_api_v1_voice_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/transcribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transcribe Voice
         * @description Synchronously transcribes audio, translates to English via Bhashini,
         *     and extracts structured claim fields.
         *     Does NOT return spoof score or risk metrics (claimant privacy safety).
         *     Supports text-only translation for browser Web Speech API fallbacks.
         */
        post: operations["transcribe_voice_api_v1_voice_transcribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description Returns graph nodes and edges for visualization.
         *     If no focus is provided, returns top rings overview.
         */
        get: operations["get_graph_api_v1_network_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/rings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rings
         * @description Lists detected fraud rings with pagination and filtering.
         */
        get: operations["list_rings_api_v1_network_rings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/rings/{ring_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ring
         * @description Returns detailed case overview of a fraud ring with timeline and focused graph.
         */
        get: operations["get_ring_api_v1_network_rings__ring_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/rings/{ring_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Ring Status Endpoint
         * @description Updates the operational governance status of a fraud ring.
         *     Requires a non-empty note when setting status to 'confirmed' or 'dismissed'.
         */
        post: operations["update_ring_status_endpoint_api_v1_network_rings__ring_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/rings/{ring_id}/report.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ring Json Report
         * @description Downloads structured JSON case file for an identified fraud ring.
         */
        get: operations["get_ring_json_report_api_v1_network_rings__ring_id__report_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network/rings/{ring_id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ring Pdf Report
         * @description Downloads formal A4 PDF case file for an identified fraud ring.
         */
        get: operations["get_ring_pdf_report_api_v1_network_rings__ring_id__report_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Returns dashboard executive overview KPIs:
         *     - claims_today, fast_tracked, flagged, flagged_rate
         *     - top_reasons, sparkline_7d, open_rings
         */
        get: operations["get_summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trends
         * @description Returns longitudinal time-series analytics, risk distributions,
         *     modality breakdowns, recycled evidence spikes, and decision velocity.
         */
        get: operations["get_trends_api_v1_analytics_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AadhaarQrStatus */
        AadhaarQrStatus: {
            /** Found */
            found: boolean;
            /** Signature Valid */
            signature_valid: boolean;
            /** Mode */
            mode: string;
            /** Comparisons */
            comparisons: components["schemas"]["QrComparison"][];
            /** Photo Similarity */
            photo_similarity: number;
        };
        /** ActionItem */
        ActionItem: {
            /** Id */
            id: number;
            /** Claim Id */
            claim_id?: string | null;
            /** Result Id */
            result_id?: string | null;
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /** From Status */
            from_status?: string | null;
            /** To Status */
            to_status?: string | null;
            /** Reason Category */
            reason_category?: string | null;
            /** Claimant Message */
            claimant_message?: string | null;
            /** Internal Note */
            internal_note?: string | null;
            /** Slots To Resubmit */
            slots_to_resubmit?: string[];
            /** Created At */
            created_at: string;
        };
        /** AnalysisResult */
        AnalysisResult: {
            /** Id */
            id: string;
            /** Claim Id */
            claim_id?: string | null;
            /** Mode */
            mode: string;
            /** Created At */
            created_at: string;
            image?: components["schemas"]["PipelineScore"] | null;
            document?: components["schemas"]["PipelineScore"] | null;
            /** Identity */
            identity?: unknown | null;
            claim?: components["schemas"]["PipelineScore"] | null;
            overall: components["schemas"]["OverallScore"];
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Detector Status */
            detector_status: components["schemas"]["DetectorStatus"][];
            /** Quality Warnings */
            quality_warnings: components["schemas"]["QualityWarning"][];
            /** Artifacts */
            artifacts: Record<string, never>;
            /** Versions */
            versions: {
                [key: string]: string;
            };
            /** Location */
            location?: Record<string, never> | null;
            voice?: components["schemas"]["PipelineScore"] | null;
            voice_details?: components["schemas"]["VoiceDetails"] | null;
            liveness?: components["schemas"]["LivenessStatus"] | null;
            aadhaar_qr?: components["schemas"]["AadhaarQrStatus"] | null;
            story?: components["schemas"]["StoryStatus"] | null;
            /** Links */
            links?: components["schemas"]["Link"][] | null;
            decision?: components["schemas"]["Decision"] | null;
            /** Image Results */
            image_results?: components["schemas"]["PipelineScore"][] | null;
            why_this_score?: components["schemas"]["WhyThisScore"] | null;
            /** Why This Score Items */
            why_this_score_items?: components["schemas"]["WhyThisScoreItem"][] | null;
            /** Checks Run */
            checks_run?: components["schemas"]["CheckRunItem"][] | null;
            /** Top Reasons */
            top_reasons?: string[] | null;
            /** Recommended Action */
            recommended_action?: string | null;
            /**
             * Summary Source
             * @default template
             */
            summary_source: string | null;
        };
        /** BBox */
        BBox: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
        };
        /** Body_analyze_claim_api_v1_analyze_claim_post */
        Body_analyze_claim_api_v1_analyze_claim_post: {
            /**
             * Image
             * @default []
             */
            image: string[];
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Files
             * @default []
             */
            files: string[];
            /** Document */
            document?: string | null;
            /** Id Photo */
            id_photo?: string | null;
            /** Selfie */
            selfie?: string | null;
            /** Metadata */
            metadata?: string | null;
        };
        /** Body_analyze_document_api_v1_analyze_document_post */
        Body_analyze_document_api_v1_analyze_document_post: {
            /** File */
            file?: string | null;
            /** Document */
            document?: string | null;
        };
        /** Body_analyze_image_api_v1_analyze_image_post */
        Body_analyze_image_api_v1_analyze_image_post: {
            /** File */
            file?: string | null;
            /** Image */
            image?: string | null;
        };
        /** Body_create_claim_api_v1_claims_post */
        Body_create_claim_api_v1_claims_post: {
            /** Policy Id */
            policy_id: string;
            /** Claim Type */
            claim_type: string;
            /** Peril */
            peril: string;
            /** Incident Date */
            incident_date: string;
            /**
             * Incident Time
             * @default
             */
            incident_time: string | null;
            /**
             * Location
             * @default {}
             */
            location: string | null;
            /**
             * Claimed Amount
             * @default 0
             */
            claimed_amount: number;
            /**
             * Damaged Items
             * @default []
             */
            damaged_items: string | null;
            /**
             * Description Text
             * @default
             */
            description_text: string | null;
            /**
             * Description Lang
             * @default en
             */
            description_lang: string | null;
            /** Consent */
            consent: boolean;
            /** Liveness Session Id */
            liveness_session_id?: string | null;
            /**
             * Evidence
             * @default []
             */
            evidence: string[];
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Files
             * @default []
             */
            files: string[];
            /** Slot Names */
            slot_names?: string | null;
            /** Capture Sources */
            capture_sources?: string | null;
            /** Evidence Metadata */
            evidence_metadata?: string | null;
            /** Id Photo */
            id_photo?: string | null;
            /**
             * Id Capture Source
             * @default upload
             */
            id_capture_source: string | null;
            /** Selfie */
            selfie?: string | null;
            /**
             * Selfie Capture Source
             * @default camera
             */
            selfie_capture_source: string | null;
            /** Voice Audio */
            voice_audio?: string | null;
            /**
             * Consent Voice Processing
             * @default false
             */
            consent_voice_processing: boolean | null;
        };
        /** Body_resubmit_evidence_api_v1_claims__id__resubmit_post */
        Body_resubmit_evidence_api_v1_claims__id__resubmit_post: {
            /**
             * Evidence
             * @default []
             */
            evidence: string[];
            /**
             * Images
             * @default []
             */
            images: string[];
            /**
             * Files
             * @default []
             */
            files: string[];
        };
        /** Body_transcribe_voice_api_v1_voice_transcribe_post */
        Body_transcribe_voice_api_v1_voice_transcribe_post: {
            /** File */
            file?: string | null;
            /**
             * Language
             * @default hi
             */
            language: string;
            /** Text */
            text?: string | null;
        };
        /** Body_verify_liveness_endpoint_api_v1_identity_liveness_verify_post */
        Body_verify_liveness_endpoint_api_v1_identity_liveness_verify_post: {
            /** Session Id */
            session_id: string;
            /** Nonce */
            nonce: string;
            /** Frame Metadata */
            frame_metadata?: string | null;
            /** Frames */
            frames: string[];
        };
        /** ChallengeStatus */
        ChallengeStatus: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /** Ms */
            ms: number;
        };
        /** CheckRunItem */
        CheckRunItem: {
            /** Detector */
            detector: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number;
            /** Reason */
            reason?: string | null;
        };
        /** ClaimantClaimSummary */
        ClaimantClaimSummary: {
            /** Claim Id */
            claim_id: string;
            /** Policy Label */
            policy_label: string;
            /** Claim Type */
            claim_type: string;
            /** Submitted At */
            submitted_at: string;
            /** Status */
            status: string;
            /** Last Update */
            last_update: string;
        };
        /** ClaimantDecision */
        ClaimantDecision: {
            /** Outcome */
            outcome: string;
            /** Reason Category Label */
            reason_category_label: string;
            /** Claimant Message */
            claimant_message: string;
            /** Next Steps */
            next_steps?: string[];
            /**
             * Can Resubmit
             * @default false
             */
            can_resubmit: boolean;
            /** Slots To Resubmit */
            slots_to_resubmit?: string[];
        };
        /** ClaimantEvidenceTimelineItem */
        ClaimantEvidenceTimelineItem: {
            /** Slot */
            slot: string;
            /** File Label */
            file_label: string;
            /** State */
            state: string;
            /** Updated At */
            updated_at: string;
        };
        /** ClaimantStatusResponse */
        ClaimantStatusResponse: {
            /** Claim Id */
            claim_id: string;
            /** Status */
            status: string;
            /** Timeline */
            timeline?: components["schemas"]["TimelineStep"][];
            decision?: components["schemas"]["ClaimantDecision"] | null;
        };
        /** Decision */
        Decision: {
            /** Status */
            status: string;
            /** By */
            by: string;
            /** At */
            at: string;
            /** Reason Code */
            reason_code: string;
            /** Claimant Message */
            claimant_message: string;
            /** Internal Note */
            internal_note: string;
        };
        /** DecisionDraftRequest */
        DecisionDraftRequest: {
            /** Action */
            action: string;
            /** Reason Category */
            reason_category: string;
            /** Investigator Note */
            investigator_note?: string | null;
        };
        /** DecisionDraftResponse */
        DecisionDraftResponse: {
            /** Claimant Message En */
            claimant_message_en: string;
            /** Claimant Message Hi */
            claimant_message_hi: string;
            /** Next Steps */
            next_steps?: string[];
            /** Slots To Resubmit */
            slots_to_resubmit?: string[];
            /** Source */
            source: string;
        };
        /** DecisionSubmitRequest */
        DecisionSubmitRequest: {
            /** Action */
            action: string;
            /** Reason Category */
            reason_category: string;
            /**
             * Claimant Message
             * @default
             */
            claimant_message: string | null;
            /** Claimant Message En */
            claimant_message_en?: string | null;
            /** Claimant Message Hi */
            claimant_message_hi?: string | null;
            /** Internal Note */
            internal_note?: string | null;
            /** Slots To Resubmit */
            slots_to_resubmit?: string[];
        };
        /** DetectorStatus */
        DetectorStatus: {
            /** Detector */
            detector: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number;
            /** Error */
            error?: string | null;
        };
        /** Evidence */
        Evidence: {
            /** Id */
            id: string;
            /**
             * Kind
             * @default risk
             */
            kind: string;
            /**
             * Raw Score
             * @default 0.5
             */
            raw_score: number;
            /**
             * Calibrated Score
             * @default 0.5
             */
            calibrated_score: number;
            /**
             * Weight
             * @default 0.5
             */
            weight: number;
            /**
             * Effective Weight
             * @default 0.5
             */
            effective_weight: number;
            /**
             * Severity
             * @default medium
             */
            severity: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Field */
            field?: string | null;
            bbox?: components["schemas"]["BBox"] | null;
            /** Bboxes */
            bboxes?: unknown[] | null;
            /** Details */
            details?: Record<string, never> | null;
            /** Artifact */
            artifact?: string | null;
            /** Pipeline */
            pipeline?: string | null;
            /** Source */
            source?: string | null;
            /** Contribution */
            contribution?: number | null;
            /** Contribution Pct */
            contribution_pct?: number | null;
            /** Rank */
            rank?: number | null;
            /** Pipeline Input */
            pipeline_input?: string | null;
            /**
             * Page
             * @default 1
             */
            page: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /** Mode */
            mode: string;
            /** Overall Risk */
            overall_risk: number;
            /** Overall Band */
            overall_band: string;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /**
             * Evidence Count
             * @default 0
             */
            evidence_count: number;
            /** Top Reason */
            top_reason?: string | null;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Items */
            items: components["schemas"]["HistoryItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Steps */
            steps: components["schemas"]["StepStatus"][];
            /** Result Id */
            result_id?: string | null;
            /** Error */
            error?: string | null;
        };
        /** LanguageItem */
        LanguageItem: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Native */
            native: string;
        };
        /** Link */
        Link: {
            /** Result Id */
            result_id: string;
            /** Reason */
            reason: string;
        };
        /** LivenessSessionResponse */
        LivenessSessionResponse: {
            /** Session Id */
            session_id: string;
            /** Nonce */
            nonce: string;
            /** Challenges */
            challenges: string[];
            /** Spoken Code */
            spoken_code: string;
            /** Expires At */
            expires_at: string;
        };
        /** LivenessStatus */
        LivenessStatus: {
            /** Performed */
            performed: boolean;
            /** Passed */
            passed: boolean;
            /** Code Match */
            code_match: boolean;
            /** Challenges */
            challenges: components["schemas"]["ChallengeStatus"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            user: components["schemas"]["UserProfile"];
        };
        /** MeResponse */
        MeResponse: {
            user: components["schemas"]["UserProfile"];
        };
        /** OverallScore */
        OverallScore: {
            /** Risk */
            risk: number;
            /** Band */
            band: string;
            /** Confidence */
            confidence: string;
            /** Summary */
            summary: string;
        };
        /** OverallWhy */
        OverallWhy: {
            /**
             * Formula
             * @default
             */
            formula: string;
            /**
             * Pipeline Risks
             * @default {}
             */
            pipeline_risks: {
                [key: string]: number;
            };
            /**
             * Overrides Applied
             * @default []
             */
            overrides_applied: string[];
        };
        /** PipelineScore */
        PipelineScore: {
            /** Pipeline */
            pipeline: string;
            /** Risk */
            risk: number;
            /** Authenticity */
            authenticity: number;
            /** Band */
            band: string;
            /** Confidence */
            confidence: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** PipelineWhy */
        PipelineWhy: {
            /**
             * Evidence Contributions
             * @default []
             */
            evidence_contributions: components["schemas"]["WhyThisScoreItem"][];
            /**
             * Formula
             * @default
             */
            formula: string;
            /**
             * Overrides Applied
             * @default []
             */
            overrides_applied: string[];
            /**
             * Quality Gates Applied
             * @default []
             */
            quality_gates_applied: components["schemas"]["QualityGateApplied"][];
        };
        /** PolicyItem */
        PolicyItem: {
            /** Policy Number */
            policy_number: string;
            /** Claim Type */
            claim_type: string;
            /** Sum Insured */
            sum_insured: number;
            /** Start Date */
            start_date: string;
            /** End Date */
            end_date: string;
            /** Vehicle Or Asset */
            vehicle_or_asset: string;
            /** Details */
            details?: Record<string, never> | null;
        };
        /** QrComparison */
        QrComparison: {
            /** Field */
            field: string;
            /** Printed */
            printed: string;
            /** Qr */
            qr: string;
            /** Match */
            match: boolean;
        };
        /** QualityGateApplied */
        QualityGateApplied: {
            /** Detector */
            detector: string;
            /** Factor */
            factor: number;
            /** Reason */
            reason: string;
        };
        /** QualityWarning */
        QualityWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** QueueItem */
        QueueItem: {
            /** Claim Id */
            claim_id: string;
            /** Result Id */
            result_id?: string | null;
            /** Claimant Name */
            claimant_name: string;
            /** Type */
            type: string;
            /** Submitted At */
            submitted_at: string;
            /** Band */
            band: string;
            /** Overall Risk */
            overall_risk: number;
            /** Top Reason */
            top_reason: string;
            /** Status */
            status: string;
            /**
             * Can Fast Track
             * @default false
             */
            can_fast_track: boolean;
        };
        /** QueueResponse */
        QueueResponse: {
            /** Items */
            items: components["schemas"]["QueueItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** StatusUpdateRequest */
        StatusUpdateRequest: {
            /** Status */
            status: string;
            /** Note */
            note?: string | null;
        };
        /** StepStatus */
        StepStatus: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** StoryStatus */
        StoryStatus: {
            /**
             * Contradictions
             * @default []
             */
            contradictions: unknown[];
            /**
             * Consistent Points
             * @default []
             */
            consistent_points: unknown[];
            /**
             * Source
             * @default rules
             */
            source: string;
            /**
             * Note
             * @default For investigator review, not part of the score
             */
            note: string;
        };
        /** TimelineStep */
        TimelineStep: {
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Date */
            date: string;
        };
        /** TranscribeResponse */
        TranscribeResponse: {
            /** Language */
            language: string;
            /** Duration S */
            duration_s: number;
            /** Transcript */
            transcript: string;
            /** Translation En */
            translation_en: string;
            extracted: components["schemas"]["VoiceExtractedFields"];
            /** Source */
            source: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Preferred Lang */
            preferred_lang: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoiceDetails */
        VoiceDetails: {
            /** Language */
            language?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Transcript */
            transcript?: string | null;
            /** Translation En */
            translation_en?: string | null;
            extracted?: components["schemas"]["VoiceExtracted"] | null;
            spoof?: components["schemas"]["VoiceSpoof"] | null;
            /** Status */
            status?: string | null;
        };
        /** VoiceExtracted */
        VoiceExtracted: {
            /** Incident Date */
            incident_date?: string | null;
            /** Incident Time */
            incident_time?: string | null;
            /** Amount Claimed */
            amount_claimed?: number | null;
            /** Damaged Items */
            damaged_items?: string[] | null;
            /** Location Text */
            location_text?: string | null;
            /** Vehicle Registration */
            vehicle_registration?: string | null;
            /** Peril */
            peril?: string | null;
        };
        /** VoiceExtractedFields */
        VoiceExtractedFields: {
            /** Incident Type */
            incident_type?: string | null;
            /** Peril */
            peril?: string | null;
            /** Incident Date */
            incident_date?: string | null;
            /** Incident Time */
            incident_time?: string | null;
            /** Location Text */
            location_text?: string | null;
            /** Vehicle Registration */
            vehicle_registration?: string | null;
            /** Damaged Items */
            damaged_items?: string[];
            /** Amount Claimed */
            amount_claimed?: number | null;
        };
        /** VoiceSpoof */
        VoiceSpoof: {
            /** Probability */
            probability?: number | null;
            /** Band */
            band?: string | null;
            /** Segments */
            segments?: components["schemas"]["VoiceSpoofSegment"][] | null;
        };
        /** VoiceSpoofSegment */
        VoiceSpoofSegment: {
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Score */
            score: number;
        };
        /** WhyThisScore */
        WhyThisScore: {
            image?: components["schemas"]["PipelineWhy"] | null;
            document?: components["schemas"]["PipelineWhy"] | null;
            identity?: components["schemas"]["PipelineWhy"] | null;
            voice?: components["schemas"]["PipelineWhy"] | null;
            claim?: components["schemas"]["PipelineWhy"] | null;
            overall?: components["schemas"]["OverallWhy"] | null;
            /** Items */
            items?: components["schemas"]["WhyThisScoreItem"][] | null;
        };
        /** WhyThisScoreItem */
        WhyThisScoreItem: {
            /** Evidence Id */
            evidence_id: string;
            /** Title */
            title: string;
            /** W */
            w: number;
            /** P */
            p: number;
            /** Push */
            push: number;
            /** Contribution Pct */
            contribution_pct: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    analyze_image_api_v1_analyze_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_image_api_v1_analyze_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_document_api_v1_analyze_document_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_document_api_v1_analyze_document_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_claim_api_v1_analyze_claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_claim_api_v1_analyze_claim_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_result_api_v1_results__result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_analysis_result_api_v1_results__result_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_evidence_api_v1_results__result_id__evidence_get: {
        parameters: {
            query?: {
                /** @description Filter by pipeline (e.g. image, document, img_1, doc) */
                pipeline?: string | null;
                /** @description Filter by severity (low, medium, high) */
                severity?: string | null;
                /** @description Filter by kind (risk, authenticity, info) */
                kind?: string | null;
            };
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_history_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                mode?: string | null;
                band?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_json_report_api_v1_results__result_id__report_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pdf_report_api_v1_results__result_id__report_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_timeline_api_v1_results__result_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_signed_url_api_v1_artifacts__result_id___name__url_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__result_id___name__get: {
        parameters: {
            query?: {
                sig?: string;
                exp?: number;
            };
            header?: never;
            path: {
                result_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_policies_api_v1_policies_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyItem"][];
                };
            };
        };
    };
    create_claim_api_v1_claims_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_claim_api_v1_claims_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_claims_api_v1_claims_mine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimantClaimSummary"][];
                };
            };
        };
    };
    get_claim_status_api_v1_claims__id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimantStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claim_evidence_timeline_api_v1_claims__id__evidence_timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimantEvidenceTimelineItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resubmit_evidence_api_v1_claims__id__resubmit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_resubmit_evidence_api_v1_claims__id__resubmit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fast_track_claim_api_v1_claims__id__fast_track_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_fast_track_claim_api_v1_claims__id__fast_track_undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claim_actions_api_v1_claims__id__actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claim_entities_endpoint_api_v1_claims__id__entities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_claim_network_endpoint_api_v1_claims__id__network_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_triage_queue_api_v1_queue_get: {
        parameters: {
            query?: {
                /** @description LOW | MEDIUM | HIGH */
                band?: string | null;
                /** @description motor | health | property */
                type?: string | null;
                /** @description submitted | under_review | needs_evidence | approved | rejected */
                status?: string | null;
                /** @description Search query */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_decision_api_v1_results__id__decision_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Result ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_decision_api_v1_results__id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Result ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_liveness_session_api_v1_identity_liveness_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessSessionResponse"];
                };
            };
        };
    };
    verify_liveness_endpoint_api_v1_identity_liveness_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_verify_liveness_endpoint_api_v1_identity_liveness_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supported_languages_api_v1_voice_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageItem"][];
                };
            };
        };
    };
    transcribe_voice_api_v1_voice_transcribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_transcribe_voice_api_v1_voice_transcribe_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscribeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_v1_network_graph_get: {
        parameters: {
            query?: {
                focus_type?: string | null;
                focus_id?: string | null;
                hops?: number;
                min_strength?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rings_api_v1_network_rings_get: {
        parameters: {
            query?: {
                min_score?: number | null;
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ring_api_v1_network_rings__ring_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ring_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ring_status_endpoint_api_v1_network_rings__ring_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ring_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ring_json_report_api_v1_network_rings__ring_id__report_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ring_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ring_pdf_report_api_v1_network_rings__ring_id__report_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ring_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_trends_api_v1_analytics_trends_get: {
        parameters: {
            query?: {
                range?: string;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
