import os
import io
import json
import hashlib
import datetime
from typing import Dict, Any, Optional
from pathlib import Path

from ..schemas.result import AnalysisResult

# ReportLab imports
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image as RLImage,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas

def format_inr(amount: float) -> str:
    """Formats amount in standard Indian Currency format (₹ 1,23,456.78)."""
    s = f"{amount:.2f}"
    parts = s.split(".")
    integer_part = parts[0]
    decimal_part = parts[1]
    if len(integer_part) <= 3:
        formatted = integer_part
    else:
        last3 = integer_part[-3:]
        other = integer_part[:-3]
        groups = []
        while len(other) > 2:
            groups.insert(0, other[-2:])
            other = other[:-2]
        if other:
            groups.insert(0, other)
        groups.append(last3)
        formatted = ",".join(groups)
    return f"₹ {formatted}.{decimal_part}"

class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas for Page X of Y and permanent legal disclaimer footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_footer(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#4B5563"))
        disclaimer = "Generated by Lucen AI. For investigative triage only; not an automated denial of claim."
        self.drawString(54, 25, disclaimer)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(541, 25, page_str)
        self.setStrokeColor(colors.HexColor("#E5E7EB"))
        self.setLineWidth(0.5)
        self.line(54, 38, 541, 38)
        self.restoreState()


def generate_json_report(result: AnalysisResult) -> Dict[str, Any]:
    """Returns the full result dictionary plus an audit verification block."""
    result_dict = result.model_dump()
    raw_bytes = json.dumps(result_dict, sort_keys=True).encode("utf-8")
    content_hash = hashlib.sha256(raw_bytes).hexdigest()
    result_dict["audit"] = {
        "investigator": "System Auditor",
        "exported_at": datetime.datetime.utcnow().isoformat(),
        "sha256": content_hash,
        "format_version": "1.0.0"
    }
    return result_dict


def generate_pdf_report(result: AnalysisResult) -> bytes:
    """Generates an executive multi-page A4 forensic audit report in PDF format."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=54,
        rightMargin=54,
        topMargin=40,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#111827"),
    )
    h1_style = ParagraphStyle(
        "H1",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#1F2937"),
        spaceBefore=12,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#374151"),
    )
    bold_style = ParagraphStyle(
        "BoldBody",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#1F2937"),
    )
    code_style = ParagraphStyle(
        "CodeText",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#1E3A8A"),
    )

    story = []

    # Header block
    band = result.overall.band.upper()
    band_color = colors.HexColor("#DC2626") if band == "HIGH" else (
        colors.HexColor("#D97706") if band in ("MED", "MEDIUM") else colors.HexColor("#16A34A")
    )
    header_data = [
        [
            Paragraph("<b>LUCEN AI</b> | Forensic Fraud Analysis Report", title_style),
            Paragraph(f"<font color='{band_color.hexval()}'><b>{band} RISK ({result.overall.risk:.1%})</b></font>", bold_style)
        ],
        [
            Paragraph(f"<b>Result ID:</b> {result.id}<br/><b>Mode:</b> {result.mode.upper()}<br/><b>Analyzed:</b> {result.created_at}", body_style),
            Paragraph(f"<b>Confidence:</b> {result.overall.confidence.upper()}<br/><b>Export Date:</b> {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", body_style)
        ]
    ]
    header_table = Table(header_data, colWidths=[330, 157])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#3B82F6"), spaceAfter=12))

    # §1 Executive summary
    story.append(Paragraph("1. Executive Summary", h1_style))
    summary_text = result.overall.summary or "Analysis complete."
    rec_action = result.recommended_action or "Review evidence."
    exec_content = (
        f"<b>Investigation Summary:</b> {summary_text}<br/><br/>"
        f"<b>Recommended Action:</b> <font color='#1E40AF'><b>{rec_action}</b></font>"
    )
    story.append(Paragraph(exec_content, body_style))
    story.append(Spacer(1, 10))

    # §2 Score breakdown
    story.append(Paragraph("2. Pipeline Score Breakdown", h1_style))
    score_rows = [
        ["Pipeline", "Risk Score", "Authenticity", "Band", "Confidence Level"]
    ]
    if result.image:
        score_rows.append(["Image Forensics", f"{result.image.risk:.1%}", f"{result.image.authenticity:.1%}", result.image.band, result.image.confidence.upper()])
    if result.document:
        score_rows.append(["Document Forensics", f"{result.document.risk:.1%}", f"{result.document.authenticity:.1%}", result.document.band, result.document.confidence.upper()])
    score_rows.append(["Composite Overall", f"{result.overall.risk:.1%}", f"{round(1.0 - result.overall.risk, 4):.1%}", result.overall.band, result.overall.confidence.upper()])

    score_table = Table(score_rows, colWidths=[120, 85, 85, 95, 102])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor("#1F2937")),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8.5),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0,0), (-1,-1), 5),
        ('ALIGN', (1,0), (-1,-1), 'CENTER'),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 10))

    # §3 Top reasons
    story.append(Paragraph("3. Top Fraud Indicators & Key Reasons", h1_style))
    reasons = result.top_reasons or ["No major suspicious anomalies detected."]
    reasons_p = "<br/>".join([f"&bull; <b>{r}</b>" for r in reasons])
    story.append(Paragraph(reasons_p, body_style))
    story.append(Spacer(1, 10))

    # §4 & §5 Artifact previews (Image / Document boxes)
    base_art_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../data/runtime/artifacts", result.id))
    has_image_art = False
    if os.path.isdir(base_art_dir):
        # Check for preview images or annotated boxes
        candidate_images = ["page_1_boxes.png", "heatmap.png", "preview_img_1.jpg", "preview_doc.png"]
        for c_img in candidate_images:
            img_path = os.path.join(base_art_dir, c_img)
            if os.path.isfile(img_path):
                try:
                    story.append(Paragraph(f"4. Key Forensic Artifact ({c_img})", h1_style))
                    rl_img = RLImage(img_path, width=280, height=200)
                    story.append(rl_img)
                    story.append(Spacer(1, 8))
                    has_image_art = True
                    break
                except Exception:
                    pass

    if not has_image_art:
        story.append(Paragraph("4. Key Forensic Artifacts", h1_style))
        story.append(Paragraph("Artifacts recorded: Heatmap & bounding boxes rendered into session store.", body_style))
        story.append(Spacer(1, 8))

    # §6 Evidence table
    story.append(Paragraph("5. Detailed Evidence Catalog", h1_style))
    ev_header = ["Rank", "ID", "Indicator Title", "Severity", "Calibrated", "Weight", "Contrib %"]
    ev_rows = [ev_header]
    for e in (result.evidence or [])[:12]:
        c_pct = f"{e.contribution_pct:.1f}%" if e.contribution_pct is not None else "-"
        w_str = f"{e.effective_weight:.2f}" if e.effective_weight is not None else f"{e.weight:.2f}"
        cal_str = f"{e.calibrated_score:.2f}" if e.calibrated_score is not None else f"{e.raw_score:.2f}"
        rank_str = str(e.rank) if e.rank else "-"
        ev_rows.append([
            rank_str,
            e.id,
            Paragraph(e.title or e.reason or "", body_style),
            e.severity.upper(),
            cal_str,
            w_str,
            c_pct
        ])

    if len(ev_rows) > 1:
        ev_table = Table(ev_rows, colWidths=[35, 80, 185, 55, 45, 42, 45])
        ev_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7EB")),
            ('PADDING', (0,0), (-1,-1), 4),
            ('ALIGN', (0,0), (0,-1), 'CENTER'),
            ('ALIGN', (3,0), (-1,-1), 'CENTER'),
        ]))
        story.append(ev_table)
    else:
        story.append(Paragraph("No active evidence items triggered.", body_style))
    story.append(Spacer(1, 10))

    # §7 Why this score
    story.append(Paragraph("6. Scoring Methodology & Transparency", h1_style))
    why = result.why_this_score
    why_text = ""
    if why and why.overall:
        why_text += f"<b>Overall Blend Formula:</b><br/>{why.overall.formula}<br/><br/>"
    if why and why.image:
        why_text += f"<b>Image Fusion Formula:</b><br/>{why.image.formula}<br/>"
    if why and why.document:
        why_text += f"<b>Document Fusion Formula:</b><br/>{why.document.formula}<br/>"
    if not why_text:
        why_text = f"<b>Blend:</b> 0.7 * max(R) + 0.3 * mean(R) = {result.overall.risk:.4f}"
    story.append(Paragraph(why_text, code_style))
    story.append(Spacer(1, 10))

    # §8 Checks run table
    story.append(Paragraph("7. Automated Checks & Pipeline Audits", h1_style))
    chk_rows = [["Detector / Check", "Status", "Duration (ms)", "Diagnostic Note"]]
    for chk in (result.checks_run or []):
        chk_rows.append([
            chk.detector,
            chk.status.upper(),
            str(chk.duration_ms),
            Paragraph(chk.reason or "Completed normally", body_style)
        ])

    if len(chk_rows) > 1:
        chk_table = Table(chk_rows, colWidths=[130, 60, 75, 222])
        chk_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7EB")),
            ('PADDING', (0,0), (-1,-1), 4),
            ('ALIGN', (1,0), (2,-1), 'CENTER'),
        ]))
        story.append(chk_table)
    story.append(Spacer(1, 10))

    # §9 Chain of custody
    story.append(Paragraph("8. Chain of Custody & Audit Integrity", h1_style))
    audit_data = [
        ["Audit Field", "Value"],
        ["Result UID", result.id],
        ["Created Timestamp", result.created_at],
        ["Engine Version", result.versions.get("engine", "lucen-2.0")],
        ["Image AI Model", result.versions.get("detector", "Ateeqq/ai-vs-human-image-detector")],
        ["Calibration Date", result.versions.get("calibration_date", "2026-10-02")],
        ["Git Commit Reference", result.versions.get("git_commit", "e8d47bf")],
    ]
    audit_table = Table(audit_data, colWidths=[150, 337])
    audit_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(audit_table)

    # Build PDF with NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()


def generate_ring_report_json(ring_data: Dict[str, Any]) -> Dict[str, Any]:
    """Generates a complete structured JSON case file for an identified fraud ring."""
    case_file = {
        "case_file_version": "1.0.0",
        "generated_at": datetime.datetime.utcnow().isoformat(),
        "ring_id": ring_data.get("ring_id"),
        "ring_score": ring_data.get("ring_score"),
        "band": ring_data.get("band"),
        "status": ring_data.get("status"),
        "claims_count": ring_data.get("claims_count"),
        "claimants_count": ring_data.get("claimants_count"),
        "total_claimed_amount": ring_data.get("total_claimed_amount"),
        "first_seen": ring_data.get("first_seen"),
        "last_seen": ring_data.get("last_seen"),
        "data_source": ring_data.get("data_source", "real"),
        "reasons": ring_data.get("reasons", []),
        "shared_identifiers": ring_data.get("shared", []),
        "claims": ring_data.get("claims", []),
        "timeline": ring_data.get("timeline", []),
        "audit_history": ring_data.get("audit", []),
        "disclaimer": (
            "NOTICE: Fraud ring associations represent probabilistic intelligence based on "
            "shared digital identifiers and multi-claim forensic patterns. Ring confirmation is an "
            "investigator-governed decision. Network indicators alone do not constitute legal proof of fraud."
        )
    }
    return case_file


def generate_ring_report_pdf(ring_data: Dict[str, Any]) -> bytes:
    """Generates an A4 PDF Case File for an identified fraud ring."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('Title', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=20, leading=24, textColor=colors.HexColor("#0B1220"), alignment=0)
    h1_style = ParagraphStyle('H1', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=13, leading=17, textColor=colors.HexColor("#0F1B2D"), spaceBefore=12, spaceAfter=6)
    body_style = ParagraphStyle('Body', parent=styles['BodyText'], fontName='Helvetica', fontSize=9, leading=13, textColor=colors.HexColor("#1F2937"))
    meta_style = ParagraphStyle('Meta', parent=styles['Normal'], fontName='Helvetica', fontSize=8, leading=11, textColor=colors.HexColor("#4B5563"))

    story = []

    # Title & Metadata
    story.append(Paragraph(f"Lucen AI — Fraud Ring Case File", title_style))
    story.append(Paragraph(f"Ring Identifier: <b>{ring_data.get('ring_id')}</b> | Generated: {datetime.datetime.utcnow().strftime('%d %b %Y, %H:%M UTC')}", meta_style))
    story.append(Spacer(1, 12))

    # Executive Summary Card
    band = ring_data.get("band", "LOW")
    score = ring_data.get("ring_score", 0.0)
    band_color = colors.HexColor("#DC2626") if band == "HIGH" else (colors.HexColor("#D97706") if band == "MEDIUM" else colors.HexColor("#16A34A"))

    summary_rows = [
        ["Ring Status", ring_data.get("status", "open").upper(), "Risk Band", band],
        ["Ring Score", f"{score:.2f} ({score * 100:.1f}%)", "Total Claims", str(ring_data.get("claims_count", 0))],
        ["Unique Claimants", str(ring_data.get("claimants_count", 0)), "Total Exposure", format_inr(float(ring_data.get("total_claimed_amount", 0.0)))],
        ["First Detected", ring_data.get("first_seen", "")[:10], "Last Active", ring_data.get("last_seen", "")[:10]],
    ]
    t_summary = Table(summary_rows, colWidths=[120, 123, 120, 124])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F9FAFB")),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
        ('FONTNAME', (2,0), (2,-1), 'Helvetica-Bold'),
        ('TEXTCOLOR', (3,0), (3,0), band_color),
        ('FONTNAME', (3,0), (3,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8.5),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(t_summary)
    story.append(Spacer(1, 12))

    # Key Reasons
    story.append(Paragraph("1. Primary Ring Indicators & Patterns", h1_style))
    for reason in ring_data.get("reasons", []):
        story.append(Paragraph(f"• {reason}", body_style))
    story.append(Spacer(1, 10))

    # Shared Identifiers
    story.append(Paragraph("2. Shared Digital Identifiers", h1_style))
    shared_rows = [["Entity Type", "Masked Label / Value", "Associated Claims"]]
    for item in ring_data.get("shared", []):
        shared_rows.append([
            item.get("type", "").title(),
            item.get("label", ""),
            f"{item.get('count', 0)} claims"
        ])
    t_shared = Table(shared_rows, colWidths=[130, 230, 127])
    t_shared.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(t_shared)
    story.append(Spacer(1, 10))

    # Member Claims
    story.append(Paragraph("3. Coordinated Member Claims", h1_style))
    claims_rows = [["Claim UID", "Submitted Date", "Claim Amount", "Risk Band"]]
    for c in ring_data.get("claims", []):
        claims_rows.append([
            c.get("claim_id", "")[:12],
            (c.get("submitted_at") or "")[:10],
            format_inr(float(c.get("amount", 0.0))),
            c.get("band", "LOW")
        ])
    t_claims = Table(claims_rows, colWidths=[140, 110, 137, 100])
    t_claims.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0,0), (-1,-1), 4),
        ('ALIGN', (2,1), (2,-1), 'RIGHT'),
    ]))
    story.append(t_claims)
    story.append(Spacer(1, 10))

    # Audit & Status Transitions
    story.append(Paragraph("4. Investigator Audit Log & Governance", h1_style))
    audit_rows = [["Timestamp", "Action / Transition", "Actor", "Investigator Note"]]
    for a in ring_data.get("audit", []):
        audit_rows.append([
            (a.get("created_at") or "")[:19].replace("T", " "),
            f"{a.get('from_status')} -> {a.get('to_status')}",
            a.get("actor", "investigator"),
            Paragraph(a.get("note") or "-", body_style)
        ])
    if len(audit_rows) == 1:
        audit_rows.append(["-", "Initial Detection (open)", "system", "Automated network graph detection"])
    t_audit = Table(audit_rows, colWidths=[100, 110, 87, 190])
    t_audit.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F3F4F6")),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,-1), 7.5),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E7EB")),
        ('PADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(t_audit)

    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()

